import ImgProfile from "../../assets/img/team/ulum.png";
export const dataTransaction = [
  {
    id: 1,
    img: ImgProfile,
    class: "Public Speaking",
    name: "Andika Slebew",
    purchaseId: "1121211111",
    price: "Rp 50.000",
    status: "Sudah Bayar",
    statusColor: " bg-[#ECFDF3] text-green-500",
  },
  {
    id: 2,
    img: ImgProfile,
    class: "Web Programming",
    name: "Andika Slebew",
    purchaseId: "112141214",
    price: "Rp 120.000",
    status: "Sudah Bayar",
    statusColor: "bg-[#ECFDF3] text-green-500",
  },
  {
    id: 3,
    img: ImgProfile,
    class: "Project Management",
    name: "Mery Anne",
    purchaseId: "143434444",
    price: "Rp 200.000",
    status: "Sudah Bayar",
    statusColor: "bg-[#ECFDF3] text-green-500",
  },
  {
    id: 4,
    img: ImgProfile,
    class: "Mobile Dev",
    name: "Yoga andrew",
    purchaseId: "121313132",
    price: "Rp 20.000",
    status: "Sudah Bayar",
    statusColor: "bg-[#ECFDF3] text-green-500",
  },
  {
    id: 5,
    img: ImgProfile,
    class: "English",
    name: "Sulie prikitihv",
    purchaseId: "3235252532",
    price: "Rp 200.000",
    status: "Sudah Bayar",
    statusColor: "bg-[#ECFDF3] text-green-500",
  },
  {
    id: 6,
    img: ImgProfile,
    class: "Japanese",
    name: "Kunkun",
    purchaseId: "2212132323",
    price: "Rp 400.000",
    status: "Belum Bayar",
    statusColor: " bg-[#F2F4F7] text-textLabel",
  },
  {
    id: 7,
    img: ImgProfile,
    class: "Japanese",
    name: "Kunkun",
    purchaseId: "2212132323",
    price: "Rp 400.000",
    status: "Dibatalkan",
    statusColor: "bg-[#FFDAD8] text-red-500",
  },
];
