import { LuPencil } from "react-icons/lu";
export const dataChallenge = [
  {
    id: 1,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    durasi: "20 Mar - 30 Aug 2024 ",
    desc: "Web DeveHackerEChalenge",
    descfull: "Hackerchallengaohafsaofhsfms",
  },
  {
    id: 2,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    durasi: "20 Mar - 30 Aug 2024 ",
    desc: "Hacker, Challenge",
    descfull: "Hackerchallengaohafsaofhsfms",
  },
  {
    id: 3,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    durasi: "20 Mar - 30 Aug 2024 ",
    desc: "Hacker, Challenge",
    descfull: "Hackerchallengaohafsaofhsfms",
  },
  {
    id: 4,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    durasi: "20 Mar - 30 Aug 2024 ",
    desc: "Hacker, Challenge",
    descfull: "Hackerchallengaohafsaofhsfms",
  },
  {
    id: 5,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    durasi: "20 Mar - 30 Aug 2024 ",
    desc: "Hacker, Challenge",
    descfull: "Hackerchallengaohafsaofhsfms",
  },
  {
    id: 5,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    durasi: "20 Mar - 30 Aug 2024 ",
    desc: "Hacker, Challenge",
    descfull: "Hackerchallengaohafsaofhsfms",
  },
];
