import { LuPencil } from "react-icons/lu";
export const dataEvent = [
  {
    id: 1,
    icon: <LuPencil />,
    title: "Webinar Public Speaking",
    desc: "Bergabunglah dengan kami dalam acara yang menginspirasi ini yang bertujuan untuk membekali Anda dengan keterampilan yang diperlukan untuk menjadi seorang pembicara publik yang percaya diri dan berpengaruh. ",
    time: "08.00 WIB",
    date: "11/03/2024",
    tag: "Web Development, Front-Endasdasd",
  },
  {
    id: 2,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    desc: "Belajar web development untuk pemula dari awal banget ",
    time: "08.00 WIB",
    date: "11/03/2024",
    tag: "Web Development, Front-Endasdasd",
  },
  {
    id: 3,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    desc: "Belajar web development untuk pemula dari awal banget ",
    time: "08.00 WIB",
    date: "11/03/2024",
    tag: "Web Development, Front-Endasdasd",
  },
  {
    id: 4,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    desc: "Belajar web development untuk pemula dari awal banget ",
    time: "08.00 WIB",
    date: "11/03/2024",
    tag: "Web Development, Front-Endasdasd",
  },
  {
    id: 5,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    desc: "Belajar web development untuk pemula dari awal banget ",
    time: "08.00 WIB",
    date: "11/03/2024",
    tag: "Web Development, Front-Endasdasd",
  },
  {
    id: 6,
    icon: <LuPencil />,
    title: "Webinar Pemrograman tingkat atas",
    desc: "Belajar web development untuk pemula dari awal banget ",
    time: "08.00 WIB",
    date: "11/03/2024",
    tag: "Web Development, Front-Endasdasd",
  },
];
