import { LuPencil } from "react-icons/lu";
export const dataEvent = [
  {
    id: 1,
    icon: <LuPencil />,
    title: "Webinar Public Speaking",
    desc: "Bergabunglah dengan kami dalam acara yang",
    descfull:
      "Bergabunglah dengan kami dalam acara yang menginspirasi ini yang bertujuan untuk membekali Anda dengan keterampilan yang diperlukan untuk menjadi seorang pembicara publik yang percaya diri dan berpengaruh.",
    time: "08.00 WIB",
    date: "11/03/2024",
    lok: "Zoom Meeting",
    link: "zoom.com",
    community: "Komunitas IT Yogyakarta",
    type: "Hacker",
    skill: "Web Development",
  },
  {
    id: 2,
    icon: <LuPencil />,
    title: "Workshop Python Programming",
    desc: "Tingkatkan kemampuan pemrograman Python Anda",
    descfull:
      "Ikuti workshop intensif kami yang berfokus pada pemrograman Python untuk pengembangan web dan data science. Dapatkan tips dan trik dari para ahli di bidangnya.",
    time: "10.00 WIB",
    date: "12/03/2024",
    lok: "Microsoft Teams",
    link: "teams.microsoft.com",
    community: "Komunitas Python Indonesia",
    type: "Coder",
    skill: "Python Programming",
  },
  {
    id: 3,
    icon: <LuPencil />,
    title: "Seminar Cyber Security",
    desc: "Pelajari dasar-dasar keamanan siber",
    descfull:
      "Seminar ini akan membahas dasar-dasar keamanan siber, termasuk teknik untuk melindungi data dan sistem Anda dari ancaman cyber. Ideal untuk profesional TI dan pemula.",
    time: "13.00 WIB",
    date: "13/03/2024",
    lok: "Google Meet",
    link: "meet.google.com",
    community: "Cyber Security Community",
    type: "Security Enthusiast",
    skill: "Cyber Security",
  },
  {
    id: 4,
    icon: <LuPencil />,
    title: "Bootcamp Machine Learning",
    desc: "Pelajari algoritma dan teknik machine learning",
    descfull:
      "Bootcamp ini menawarkan pendekatan praktis untuk belajar machine learning, mulai dari algoritma dasar hingga teknik lanjutan. Cocok untuk semua level keahlian.",
    time: "09.00 WIB",
    date: "14/03/2024",
    lok: "Cisco Webex",
    link: "webex.com",
    community: "AI & Machine Learning Group",
    type: "Data Scientist",
    skill: "Machine Learning",
  },
  {
    id: 5,
    icon: <LuPencil />,
    title: "Hackathon Coding Challenge",
    desc: "Ikuti kompetisi coding untuk menguji kemampuan Anda",
    descfull:
      "Bergabunglah dengan hackathon kami dan hadapi tantangan coding yang seru. Bekerja dalam tim atau individu untuk memecahkan masalah nyata dan menangkan hadiah menarik.",
    time: "15.00 WIB",
    date: "15/03/2024",
    lok: "Discord",
    link: "discord.com",
    community: "Hackathon Enthusiasts",
    type: "Developer",
    skill: "Coding",
  },
  {
    id: 6,
    icon: <LuPencil />,
    title: "Networking Event for Developers",
    desc: "Temui dan terhubung dengan developer lainnya",
    descfull:
      "Acara ini bertujuan untuk membantu para developer membangun jaringan profesional. Diskusikan proyek, temukan kolaborator, dan perluas koneksi Anda di industri.",
    time: "18.00 WIB",
    date: "16/03/2024",
    lok: "Slack",
    link: "slack.com",
    community: "Developer Network",
    type: "Networker",
    skill: "Networking",
  },
];
