import { FaLaptop } from "react-icons/fa";
import { LuBarChart } from "react-icons/lu";
import { GoStarFill } from "react-icons/go";
import ImgHackerAlgo from "../../assets/img/gambarcard/hackeralgo.jpg";
import ImgHackerWeb from "../../assets/img/gambarcard/hacker_web.jpg";
import ImgHackerMobile from "../../assets/img/gambarcard/hacker_mobile.jpg";
import ImgHustlerLead from "../../assets/img/gambarcard/hustler_leadership.jpg";
import ModernTailwind from "../../assets/img/gambarcard/fe3-moderntailwind.jpg";
import FeWebDev from "../../assets/img/gambarcard/fe1-frontendweb.jpg";
import FeHtmlCss from "../../assets/img/gambarcard/fe2-fehtmlcss.jpg";
import ReactTailwind from "../../assets/img/gambarcard/fe4-reacttailwind.jpg";
import FeWebLaravel from "../../assets/img/gambarcard/fe5-weblaravel.jpg";
import FullStack from "../../assets/img/gambarcard/fs1-fullstackdev.jpg";

export const dataCardWeb = [
  {
    img: FeWebDev,
    icon1: <FaLaptop />,
    tes: ["Front End Web"],
    titlecard: "Front End Web Development ",
    desccard: "Tes Dasar Mempelajari Front End web untuk membuka kelas hacker",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Menengah",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: FeHtmlCss,
    icon1: <FaLaptop />,
    tes: ["Front End Web", "Web"],
    titlecard: " Front End Next JS & Tailwind CSS",
    desccard: "Mengimplementasikan Tailwind CSS ke dalam React JS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ReactTailwind,
    icon1: <FaLaptop />,
    tes: ["Front End Web", "Web"],
    titlecard: "Front End React JS & Tailwind CSS",
    desccard: "Mengimplementasikan Tailwind CSS ke dalam React JS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ModernTailwind,
    icon1: <FaLaptop />,
    tes: ["Front End Web", "Web"],
    titlecard: "Modern Website Tailwind CSS ",
    desccard:
      "Mempelajari Tailwind css pada website modern dengan design trend terbaru",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: FeWebLaravel,
    icon1: <FaLaptop />,
    tes: ["Front End Web", "Web"],
    titlecard: " Front End Laravel & Tailwind CSS",
    desccard: "Mengimplementasikan Tailwind CSS ke dalam React JS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ImgHustlerLead,
    icon1: <FaLaptop />,
    tes: ["Back End Web", "Web"],
    titlecard: " Back End Web dengan Laravel",
    desccard: "Lakukan tes untuk membuka seluruh kelas Back End",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Menengah",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ImgHustlerLead,
    icon1: <FaLaptop />,
    tes: ["Back End Web", "Web"],
    titlecard: " Back End Web PHP, Laravel",
    desccard: "Mempelajari Back ed web dengan php dan laravel",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ImgHustlerLead,
    icon1: <FaLaptop />,
    tes: ["Back End Web", "Web"],
    titlecard: "Back End dengan NodeJS",
    desccard: "Mempelajari back end web dengan menggunakan  NodeJS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ImgHustlerLead,
    icon1: <FaLaptop />,
    tes: ["Back End Web", "Web"],
    titlecard: " Back End dengan ExpressJS",
    desccard: "Mempelajari back end web dengan menggunakan Express JS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: FullStack,
    icon1: <FaLaptop />,
    tes: ["Back End Web", "Web"],
    titlecard: " Back End dengan ExpressJS",
    desccard: "Mempelajari back end web dengan menggunakan Express JS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: FullStack,
    icon1: <FaLaptop />,
    tes: ["Full Stack Web", "Web"],
    titlecard: " Full Stack Web Developer",
    desccard: "Lakukan tes untuk membuka seluruh kelas full stack ",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ImgHustlerLead,
    icon1: <FaLaptop />,
    tes: ["Full Stack Web", "Web"],
    titlecard: "Front End Web Tailwind CSS",
    desccard: "Mempelajari cara front end web menggunakan tailwind css ",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ImgHustlerLead,
    icon1: <FaLaptop />,
    tes: ["Full Stack Web", "Web"],
    titlecard: " Back End Web Menggunakan Node JS",
    desccard: "Mempelajari backend web menggunakan Node JS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ImgHustlerLead,
    icon1: <FaLaptop />,
    tes: ["Full Stack Web", "Web"],
    titlecard: " Full Stack Web Dev React JS",
    desccard: "Mempelajari cara full stack dev dengan React JS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    img: ImgHustlerLead,
    icon1: <FaLaptop />,
    tes: ["Full Stack Web", "Web"],
    titlecard: " Full Stack Web Dev React JS",
    desccard: "Mempelajari cara full stack dev dengan React JS",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: false,
  },
];

export const dataSideWeb = [
  {
    title: "Front End Web Development",
    desc: "Berbagai course khusus front-end web yang bisa kamu pelajari!",
  },
  {
    title: "Back End Web Development",
    desc: "Berbagai course khusus back-end web yang bisa kamu pelajari!",
  },
  {
    title: "Full Stack Web Development",
    desc: "Berbagai course khusus full stack web yang bisa kamu pelajari!",
  },
];
