import { IoCodeSlash, IoPencil } from "react-icons/io5";
import TestWeb from "../../assets/img/gambarcard/kls-pemula-webdev.jpg";
import TestMob from "../../assets/img/gambarcard/kls-pemula-mobiledev.jpg";
import TestPS from "../../assets/img/gambarcard/tes-pm.jpg";
import TestBisnis from "../../assets/img/gambarcard/hustler_publicspeaking.jpg";
import TestDesign from "../../assets/img/gambarcard/hipster_UIUX.jpg";
import TestUI from "../../assets/img/gambarcard/hipster_UI.jpg";
import { RiSpeakFill } from "react-icons/ri";
import { CiLaptop } from "react-icons/ci";
import { FiUsers } from "react-icons/fi";

// Hacker Data
export const dataHacker = [
  {
    kelas: "Kelas Pemula Hacker",
    data: [
      {
        id: 1,
        img: TestWeb,
        tes: ["Hacker", "Pemula"],
        titlecard: "Web Dev",
        icons: [<CiLaptop />, <IoCodeSlash />],
        skill: ["Web Development", "HTML CSS"],
        desccard: "Mempelajari dasar Web Dev",
        about:
          "Kelas ini didesain untuk tingkat pemula, dan cocok untuk kamu yang baru belajar dan ingin memperdalam tentang web development. Output dari pembelajaran kelas pemula ini nantinya adalah siswa dapat mengerti dan memahami apa itu web development dengan mini studi kasus.",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: false,
        link: "/course/hacker/pemula/web",
      },
      {
        id: 2,
        img: TestMob,
        tes: ["Hacker", "Pemula"],
        icons: [<CiLaptop />, <IoCodeSlash />],
        titlecard: "Mobile Dev",
        desccard: "Mempelajari dasar Mobile Dev",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: false,
        link: "/course/hacker/pemula/mobile",
      },
    ],
  },
  {
    kelas: "Web Development",
    data: [
      {
        id: 1,
        img: TestWeb,
        tes: ["Hacker", "Web"],
        icons: [<CiLaptop />, <IoCodeSlash />],
        titlecard: "Front-End Web Dev",
        desccard: "Mempelajari Front-End Web Dev",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
        link: "/course/hacker/path-web",
      },
      {
        id: 2,
        img: TestWeb,
        tes: ["Hacker", "Web"],
        icons: [<CiLaptop />, <IoCodeSlash />],
        titlecard: "Back-End Web Dev",
        desccard: "Mempelajari Back-End Web Dev",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
        link: "/course/hacker/path-web",
      },
      {
        id: 3,
        img: TestWeb,
        icons: [<CiLaptop />, <IoCodeSlash />],
        tes: ["Hacker", "Web"],
        titlecard: "Full Stack Web Dev",
        desccard: "Mempelajari Full Stack Web Dev",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
        link: "/course/hacker/path-web",
      },
    ],
  },
  {
    kelas: "Mobile Development",
    data: [
      {
        id: 1,
        img: TestMob,
        icons: [<CiLaptop />, <IoCodeSlash />],
        tes: ["Hacker", "Mobile"],
        titlecard: "Front-End Mobile Dev",
        desccard: "Mempelajari Front-End Mob Dev",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 2,
        img: TestMob,
        icons: [<CiLaptop />, <IoCodeSlash />],
        tes: ["Hacker", "Mobile"],
        titlecard: "Back-End Mobile Dev",
        desccard: "Mempelajari Back-End Mob Dev",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 3,
        img: TestMob,
        icons: [<CiLaptop />, <IoCodeSlash />],
        tes: ["Hacker", "Mobile"],
        titlecard: "Full Stack Mobile Dev",
        desccard: "Mempelajari Full Stack Mob Dev",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
    ],
  },
];

// Hustler Data
export const dataHustler = [
  {
    kelas: "Kelas Pemula Hustler",
    data: [
      {
        id: 1,
        img: TestPS,
        icons: [<RiSpeakFill />, <CiLaptop />],
        tes: ["Hustler", "Pemula"],
        titlecard: "Introduction to Business",
        desccard: "Mempelajari dasar-dasar bisnis",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: false,
      },
      {
        id: 2,
        img: TestBisnis,
        icons: [<RiSpeakFill />, <CiLaptop />],
        tes: ["Hustler", "Pemula"],
        titlecard: "Basic Marketing",
        desccard: "Mempelajari dasar-dasar pemasaran",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: false,
      },
    ],
  },
  {
    kelas: "Public Speaking",
    data: [
      {
        id: 1,
        img: TestPS,
        icons: [<RiSpeakFill />, <CiLaptop />],
        tes: ["Hustler", "Speaking"],
        titlecard: "Effective Com",
        desccard: "Mempelajari komunikasi yang efektif",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 2,
        img: TestPS,
        icons: [<RiSpeakFill />, <CiLaptop />],
        tes: ["Hustler", "Speaking"],
        titlecard: "Persuasive Speaking",
        desccard: "Mempelajari teknik berbicara persuasif",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 3,
        img: TestPS,
        icons: [<RiSpeakFill />, <CiLaptop />],
        tes: ["Hustler", "Speaking"],
        titlecard: "Public Relations",
        desccard: "Mempelajari hubungan masyarakat",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
    ],
  },
  {
    kelas: "Advanced Business Strategies",
    data: [
      {
        id: 1,
        img: TestBisnis,
        icons: [<RiSpeakFill />, <CiLaptop />],
        tes: ["Hustler", "Business"],
        titlecard: "Market Analysis",
        desccard: "Mempelajari analisis pasar",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 2,
        img: TestBisnis,
        icons: [<RiSpeakFill />, <CiLaptop />],
        tes: ["Hustler", "Business"],
        titlecard: "Strategic Planning",
        desccard: "Mempelajari perencanaan strategis",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 3,
        img: TestBisnis,
        icons: [<RiSpeakFill />, <CiLaptop />],
        tes: ["Hustler", "Business"],
        titlecard: "Financial Management",
        desccard: "Mempelajari manajemen keuangan",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
    ],
  },
];

// Hipster Data
export const dataHipster = [
  {
    kelas: "Kelas Pemula Hipster",
    data: [
      {
        id: 1,
        img: TestDesign,
        icons: [<IoPencil />, <CiLaptop />],
        tes: ["Hipster", "Pemula"],
        titlecard: "Basic Design",
        desccard: "Mempelajari dasar-dasar desain",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: false,
      },
      {
        id: 2,
        img: TestUI,
        icons: [<IoPencil />, <CiLaptop />],
        tes: ["Hipster", "Pemula"],
        titlecard: "Introduction to UX",
        desccard: "Mempelajari dasar-dasar UX",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: false,
      },
    ],
  },
  {
    kelas: "UI UX Design",
    data: [
      {
        id: 1,
        img: TestDesign,
        icons: [<IoPencil />, <CiLaptop />],
        tes: ["Hipster", "Design"],
        titlecard: "User Interface Design",
        desccard: "Mempelajari desain antarmuka pengguna",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 2,
        img: TestDesign,
        icons: [<IoPencil />, <CiLaptop />],
        tes: ["Hipster", "Design"],
        titlecard: "User Experience Design",
        desccard: "Mempelajari pengalaman pengguna",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 3,
        img: TestDesign,
        icons: [<IoPencil />, <CiLaptop />],
        tes: ["Hipster", "Design"],
        titlecard: "Interaction Design",
        desccard: "Mempelajari desain interaksi",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
    ],
  },
  {
    kelas: "Advanced Design",
    data: [
      {
        id: 1,
        img: TestUI,
        icons: [<IoPencil />, <CiLaptop />],
        tes: ["Hipster", "Design"],
        titlecard: "Creative Thinking",
        desccard: "Mempelajari berpikir kreatif",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 2,
        img: TestUI,
        icons: [<IoPencil />, <CiLaptop />],
        tes: ["Hipster", "Design"],
        titlecard: "Graphic Design",
        desccard: "Mempelajari desain grafis tingkat lanjut",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
      {
        id: 3,
        img: TestUI,
        icons: [<IoPencil />, <CiLaptop />],
        tes: ["Hipster", "Design"],
        titlecard: "Design Leadership",
        desccard: "Mempelajari kepemimpinan dalam desain",
        icon2: <FiUsers />,
        level: "200 Siswa",
        isLocked: true,
      },
    ],
  },
];
