import { RiCodeView } from "react-icons/ri";
import TestWeb from "../../assets/img/gambarcard/kelas-beginner-web.jpg";
import TestMob from "../../assets/img/gambarcard/kelas-beginner-mob.jpg";
import { LuBarChart } from "react-icons/lu";
import { GoStarFill } from "react-icons/go";

export const dataHacker = [
  {
    id: 1,
    img: TestWeb,
    icon1: <RiCodeView />,
    tes: ["Hacker", "Pemula"],
    titlecard: "Web Dev",
    desccard: "Mempelajari dasar Web Dev",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Pemula",
    rating: "4.9 (2k)",
    isLocked: false,
  },
  {
    id: 2,
    img: TestMob,
    icon1: <RiCodeView />,
    tes: ["Hacker", "Pemula"],
    titlecard: "Mobile Dev",
    desccard: "Mempelajari dasar Mobile Dev",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Pemula",
    rating: "4.9 (2k)",
    isLocked: false,
  },
];

export const dataWeb = [
  {
    id: 1,
    img: TestWeb,
    icon1: <RiCodeView />,
    tes: ["Hacker", "Web"],
    titlecard: "Front-End Web Dev",
    desccard: "Mempelajari Front-End Web Dev",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Menengah",
    rating: "4.9 (2k)",
    isLocked: true,
  },
  {
    id: 2,
    img: TestWeb,
    icon1: <RiCodeView />,
    tes: ["Hacker", "Web"],
    titlecard: "Back-End Web Dev",
    desccard: "Mempelajari Back-End Web Dev",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Menengah",
    rating: "4.9 (2k)",
    isLocked: true,
  },
  {
    id: 3,
    img: TestWeb,
    icon1: <RiCodeView />,
    tes: ["Hacker", "Web"],
    titlecard: "Full Stack Web Dev",
    desccard: "Mempelajari Full Stack Web Dev",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: true,
  },
];

export const dataMob = [
  {
    id: 1,
    img: TestMob,
    icon1: <RiCodeView />,
    tes: ["Hacker", "Mobile"],
    titlecard: "Front-End Mobile Dev",
    desccard: "Mempelajari Front-End Mob Dev",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Menengah",
    rating: "4.9 (2k)",
    isLocked: true,
  },
  {
    id: 2,
    img: TestMob,
    icon1: <RiCodeView />,
    tes: ["Hacker", "Mobile"],
    titlecard: "Back-End Mobile Dev",
    desccard: "Mempelajari Back-End Mob Dev",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Menengah",
    rating: "4.9 (2k)",
    isLocked: true,
  },
  {
    id: 3,
    img: TestMob,
    icon1: <RiCodeView />,
    tes: ["Hacker", "Mobile"],
    titlecard: "Full Stack Mobile Dev",
    desccard: "Mempelajari Full Stack Mob Dev",
    icon2: <LuBarChart />,
    icon3: <GoStarFill />,
    level: "Level Tinggi",
    rating: "4.9 (2k)",
    isLocked: true,
  },
];
